version: '2'

services:
  db:
    image: 'postgres:14.8'
    restart: always
    container_name: cis-db-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432